### ISSUE TITLE
Decide where to put the logic for key presses

### ISSUE THREAD

**Issue by elthran** [elthran/ant-farm#1]
Right now in the game object we have:
```
        keys = pygame.key.get_pressed()
        if keys[pygame.K_a]:
            print(f"You have pressed the 'a' key.")
```
But we should move this to another file. This ticket is to decide what to do and write a basic function, like above.

**Comment by klondikemarlen** [comment]
https://www.pygame.org/docs/ref/key.html
https://www.pygame.org/docs/ref/event.html

**Comment by elthran** [comment]
@klondikemarlen The general idea is there are two classes. One is a class that the User owns. It stores his preference mapping. So when he presses his "UP" key it knows what key in the game that is.
Then there is a separate class which maps keys in the game to events in the game. So it's completely isolated from everything else and just does "IF UP PRESSED TELL GAME TO RUN EVENT Y"
But I may need help cleaning it up
